name: Linux Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
    - name: caml system packages install
      run: sudo add-apt-repository ppa:avsm/ppa ; sudo apt update ; sudo apt install opam ; # sudo apt-get install unzip opam ocaml-dune libdune-ocaml-dev ocaml-doc
    - name: Caml dependencies
      run: opam init ; opam switch create 4.14.1; eval $(opam env --switch=4.14.1) ; opam -y install lwt_ppx text lambda-term bigstring angstrom-lwt-unix pcre fileutils ANSITerminal
    - name: Build Octant
      run: eval $(opam env --switch=4.14.1) ; make
    - name: copy
      run: mkdir -p website/ ; cp _build/default/src/cli/octant.exe website/
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
          branch: linux # The branch the action should deploy to.
          folder: website/ # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch 
          single-commit: true
